### PR TITLE
draft proposal for community-contributed programs

### PR DESCRIPTION
**Pull request by claud9999**
I wanted to write a "game of life" program for my InkPlate 6 and I am hoping to "give it back" to the community for inclusion in the library. This PR includes my code in a subdirectory structure I am proposing, but I am certainly open to other organization.

### CODE REVIEW

**Comment by nitko12** [comment]
Hi,

awesome idea, 
I've changed your pull requests branch into our library revision branch which will probably be merged into master soon when we fix a few bugs encountered on our new batch of screens. 
I'll test your example there and approve the request in a minute :)

**Comment by nitko12** [comment]
I've changed your original file slightly to fit into our coding style.
Also added full screen refresh every n times to reduce image burn in :)

See the changes [here](https://github.com/e-radionicacom/Inkplate-6-Arduino-library/commit/69f244b557629ed27d9c8bf7fd230e26675cc8d8).

**Comment by claud9999** [comment]
> I've changed your original file slightly to fit into our coding style.
> Also added full screen refresh every n times to reduce image burn in :)
> 
> See the changes [here](https://github.com/e-radionicacom/Inkplate-6-Arduino-library/commit/69f244b557629ed27d9c8bf7fd230e26675cc8d8).

Thanks for the corrections and changes...I'm likely to write a couple more examples (weather app, wifi scanner, more "screen-saver" ideas...)

FYI the code does call display.clean() + display.display() whenever it "resets", which is every few minutes on average...actually I like the "burn in" shadow effect, very pleasing with gliders and other moving structures.

**Comment by claud9999** [comment]
Oh one other question, it may be documented somewhere but it seems that the 3-bit display mode does not support partial refreshes. Correct?

**Comment by nitko12** [comment]
Hi,

I'll see about removing full display updates, it does indeed give a nice result, but could result in a more long lasting burn in, 
as for weather app, there are two in our project examples, you'd might want to check them out, they're quite new :)
anyway, were looking forward to seeing more examples of use from you and the community!

As for 3 bit partial, correct, currently it is not implemented and does nothing, but we're working on it and might soon add it to library.
For now you could use halftoning and dithering on 1 bit images to make them appear as multiple shades. 

If you feel like experimenting, you can clone the revision branch which has 1 bit dithering implemented for bmp as well as jpeg images :D 
Here's a sneak peek of how that looks like :D

But beware of quite a lot of bugs as it is in testing phase and possibly not full backwards compatibility yet.
Your safest bet is to just dither in photoshop and then convert to 1 bit c array.

**Pull request merged**
